# Generated by Django 4.2.28 on 2026-02-06 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='award_date',
        ),
        migrations.RemoveField(
            model_name='award',
            name='description',
        ),
        migrations.RemoveField(
            model_name='award',
            name='title',
        ),
        migrations.RemoveField(
            model_name='career',
            name='description',
        ),
        migrations.RemoveField(
            model_name='career',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='career',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='career',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='career',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='credential_id',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='credential_url',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='expires_date',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='issued_date',
        ),
        migrations.RemoveField(
            model_name='education',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='education',
            name='description',
        ),
        migrations.RemoveField(
            model_name='education',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='education',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_date',
        ),
        migrations.AddField(
            model_name='award',
            name='award_detail',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='award',
            name='award_year',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='award',
            name='contest_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='career',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='career',
            name='leave_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='position',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='career',
            name='position_detail',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='certificate',
            name='grade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='obtained_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='certificate',
            name='score',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='admission_year',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='education',
            name='graduation_year',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='award',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='award',
            name='organizer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='career',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issuer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
